import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import {
  compareRequestPrefix,
  describeRequest,
} from "../src/context.js";
import { MODE_COMPARISON, PTC_PRESENTATION_EXAMPLE } from "../src/ptc-comparison.js";
import type { RuntimeInspection } from "../src/runtime.js";
import {
  buildRequest,
  requestStepIds,
  type SessionEvent,
  type TraceItem,
} from "../src/session.js";
import type { UnifiedRequest } from "../src/protocol.js";

interface CheckpointConfig {
  id: string;
  number: string;
  tag: string;
  previousTag: string;
  scenario: string;
  sourcePath: string;
  lessonPath: string;
  shortTitle: string;
  title: string;
  question: string;
}

interface ScenarioEvidence {
  requests: UnifiedRequest[];
  events: readonly SessionEvent[];
  inspection: RuntimeInspection | null;
  trace: TraceItem[];
  verdict: string;
}

const root = resolve(import.meta.dirname, "..");
const configs = JSON.parse(
  await readFile(resolve(root, "docs/checkpoints.json"), "utf8"),
) as CheckpointConfig[];
const primer = await readFile(resolve(root, "docs/typescript-primer.md"), "utf8");

const chapters = [];
for (const config of configs) {
  const evidence = await runTaggedScenario(config);
  verifyReconstruction(evidence);
  const commit = git("rev-list", "-n", "1", config.tag).trim();
  const source = git("show", `${config.tag}:${config.sourcePath}`);
  const lesson = git("show", `${config.tag}:${config.lessonPath}`);
  const diff = git(
    "diff",
    "--no-ext-diff",
    "--unified=3",
    config.previousTag,
    config.tag,
    "--",
    "src",
    "tests",
  );
  const requests = evidence.requests.map((request, index) => {
    const parts = describeRequest(request);
    return {
      step: index + 1,
      stepId: requestStepIds(evidence.events)[index],
      request,
      parts,
      totalApproximateTokens: parts.reduce((sum, part) => sum + part.approximateTokens, 0),
      prefix: compareRequestPrefix(evidence.requests[index - 1], request),
    };
  });
  chapters.push({
    ...config,
    commit,
    lesson,
    source: { path: config.sourcePath, content: source },
    diff,
    verdict: evidence.verdict,
    requests,
    events: evidence.events,
    trace: evidence.trace,
    graphs: buildGraphSnapshots(evidence.events, evidence.inspection, evidence.requests),
    ...(config.id === "m01"
      ? { ptc: { program: PTC_PRESENTATION_EXAMPLE, comparison: MODE_COMPARISON } }
      : {}),
  });
}

const output = {
  schemaVersion: 2,
  project: {
    name: "dsh-from-scratch",
    scenario: "火星中继站恢复审计",
    dataPolicy:
      "All traces are generated by deterministic fake LLM scenarios; token and prefix figures are teaching estimates, never provider cache usage.",
    selectedScope: {
      jsonl: false,
      overflowRetry: false,
      m06: true,
      codeRuntime: false,
      presetLoader: false,
    },
    primer,
  },
  chapters,
};

const outDir = resolve(root, "website/public/generated");
await mkdir(outDir, { recursive: true });
await writeFile(resolve(outDir, "tutorial.json"), `${JSON.stringify(output, null, 2)}\n`);
console.log(
  `generated ${chapters.length} checkpoints · ${chapters.reduce((sum, chapter) => sum + chapter.events.length, 0)} events · ${chapters.reduce((sum, chapter) => sum + chapter.requests.length, 0)} requests`,
);

async function runTaggedScenario(config: CheckpointConfig): Promise<ScenarioEvidence> {
  const checkpointRoot = await mkdtemp(resolve(root, `.tutorial-checkpoint-${config.id}-`));
  try {
    const archive = execFileSync("git", ["archive", "--format=tar", config.tag], {
      cwd: root,
      maxBuffer: 32 * 1024 * 1024,
    });
    execFileSync("tar", ["-xf", "-", "-C", checkpointRoot], {
      input: archive,
      maxBuffer: 32 * 1024 * 1024,
    });
    const output = execFileSync(
      resolve(root, "node_modules/.bin/tsx"),
      [resolve(root, "scripts/run-checkpoint.ts"), config.id, checkpointRoot],
      { cwd: root, encoding: "utf8", maxBuffer: 32 * 1024 * 1024 },
    );
    return JSON.parse(output) as ScenarioEvidence;
  } finally {
    await rm(checkpointRoot, { recursive: true, force: true });
  }
}

function verifyReconstruction(evidence: ScenarioEvidence): void {
  if (evidence.events.length === 0) return;
  const stepIds = requestStepIds(evidence.events);
  assert.equal(stepIds.length, evidence.requests.length);
  for (const [index, stepId] of stepIds.entries()) {
    assert.deepEqual(
      buildRequest(evidence.events, stepId),
      evidence.requests[index],
      `reconstructed request drifted at ${stepId}`,
    );
  }
}

function buildGraphSnapshots(
  events: readonly SessionEvent[],
  finalInspection: RuntimeInspection | null,
  requests: UnifiedRequest[],
): Array<Record<string, unknown>> {
  if (!finalInspection) return [];
  const activePlugins = new Set<string>(["session-log"]);
  const baseToolOwners = new Map(finalInspection.tools.map((tool) => [tool.name, tool.plugin]));
  const promptOwners = new Map(finalInspection.prompts.map((prompt) => [prompt.text, prompt.plugin]));
  const latestCapability = (): string | undefined =>
    [...activePlugins].reverse().find((plugin) => plugin.startsWith("capability:"));
  const snapshots: Array<Record<string, unknown>> = [];

  for (const event of events) {
    if (event.type === "runtime/plugin-mounted") activePlugins.add(event.plugin);
    if (event.type === "runtime/plugin-unmounted") activePlugins.delete(event.plugin);
    if (event.type !== "request/header") continue;

    const tools = event.tools.map((tool) => ({
      name: tool.name,
      owner: baseToolOwners.get(tool.name) ?? latestCapability() ?? "direct",
    }));
    const promptParagraphs = event.system.split("\n\n").slice(1);
    const prompts = promptParagraphs.map((text, index) => ({
      id: `prompt-${index + 1}`,
      text,
      owner: promptOwners.get(text) ?? latestCapability() ?? "base",
    }));
    const nodes = [
      ...[...activePlugins].map((plugin) => ({ id: plugin, label: plugin, kind: "plugin" })),
      ...tools.map((tool) => ({ id: `tool:${tool.name}`, label: tool.name, kind: "tool" })),
      ...prompts.map((prompt) => ({ id: prompt.id, label: "Prompt", kind: "prompt" })),
    ];
    const edges = [
      ...tools.map((tool) => ({ from: tool.owner, to: `tool:${tool.name}`, label: "contributes" })),
      ...prompts.map((prompt) => ({ from: prompt.owner, to: prompt.id, label: "contributes" })),
      ...finalInspection.relations
        .filter(
          (relation) =>
            activePlugins.has(relation.provider) && activePlugins.has(relation.consumer),
        )
        .map((relation) => ({
          from: relation.provider,
          to: relation.consumer,
          label: relation.service,
        })),
    ];
    snapshots.push({
      stepId: event.stepId,
      eventId: event.id,
      plugins: [...activePlugins],
      tools,
      prompts,
      services: finalInspection.services.filter((service) =>
        activePlugins.has(service.provider),
      ),
      relations: finalInspection.relations.filter(
        (relation) =>
          activePlugins.has(relation.provider) && activePlugins.has(relation.consumer),
      ),
      nodes,
      edges,
    });
  }
  if (snapshots.length === 0) {
    for (const [index, request] of requests.entries()) {
      snapshots.push({
        stepId: `step-${index + 1}`,
        eventId: index + 1,
        plugins: finalInspection.plugins,
        tools: finalInspection.tools,
        prompts: finalInspection.prompts,
        services: finalInspection.services,
        relations: finalInspection.relations,
        nodes: [
          ...finalInspection.plugins.map((plugin) => ({ id: plugin, label: plugin, kind: "plugin" })),
          ...request.tools.map((tool) => ({ id: `tool:${tool.name}`, label: tool.name, kind: "tool" })),
        ],
        edges: finalInspection.tools.map((tool) => ({
          from: tool.plugin,
          to: `tool:${tool.name}`,
          label: "contributes",
        })),
      });
    }
  }
  return snapshots;
}

function git(...args: string[]): string {
  return execFileSync("git", args, {
    cwd: root,
    encoding: "utf8",
    maxBuffer: 8 * 1024 * 1024,
  });
}
